### ISSUE TITLE
sys.isRoot doesn't always detect that the user is root

### ISSUE THREAD

**Issue by gswallow** [braceslab/a-toolbox#1]
Heya,

I'm using this project through service-systemd, setting up a demo during EC2 bootstrap.

Unless I specifically run service-systemd with sudo, service-systemd dies, saying that I need supercow powers, even though I'm running as root through EC2 user-data?

**Comment by simone-sanfratello** [comment]
Hi, thank you for reporting issue. 
Honestly, I didn't tested on EC2, but I'm going to fix asap ... I hope in this week.

**Comment by simone-sanfratello** [comment]
Hi,
I've just tried on EC2 instance "Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-916f59f4" and it works as usual, maybe the issue is about the Linux distribution, which one do you use?

**Comment by gswallow** [comment]
I used 16.04.  I believe that the issue may stem from the fact that the
shell node.js is running in at the time is a non-interactive, non-login
shell?

At least that's my guess.  I might be able to try to replicate it for you.

**Comment by simone-sanfratello** [comment]
Hi, I can't reproduce the issue and I don't understand how you use the script; anyway I updated the function to recognize root user, would you mind to retry?
